### ISSUE TITLE
Handle missing columns 

### ISSUE THREAD

**Issue by bethac07** [0x00B1/persistence#94]
If CSVs are missing certain columns (such as when some images have brightfield and some don't, or when CP throws and error and doesn't write some), handle it gracefully by filling with NA (or something comparable) rather than giving up.

**Comment by shntnu** [comment]
I created a test dataset that is identical to data_c, except that one column (`ImageQuality_ThresholdOtsu_OrigHoechst_3BW`) in `2/Image.csv` is missing 

This is the error I get

What's strange is that we get a `NOT NULL constraint failed` on the `Image.Width_OrigHoechst` column, not the `ImageQuality_ThresholdOtsu_OrigHoechst_3BW` column.
`Image.Width_OrigHoechst` is the last column of the CSV. 

So the fix for this issue may not be as simple as removing the `NOT NULL constraint` on all columns

PS - The SQLite file does get created, but without `2/Image.csv`

    $ cytominer-database ingest --no-munge -c tests/data_d/config.ini tests/data_d/ sqlite:///data_d1.sqlite
    (builtins.OSError) 
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:1: expected 230 columns but found 229 - filling the rest with NULL
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:1: INSERT failed:     NOT NULL constraint failed: Image.Width_OrigHoechst
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:2: expected 230     columns but found 229 - filling the rest with NULL
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:2: INSERT failed:     NOT NULL constraint failed: Image.Width_OrigHoechst
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:3: expected 230     columns but found 229 - filling the rest with NULL
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:3: INSERT failed:     NOT NULL constraint failed: Image.Width_OrigHoechst
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:4: expected 230     columns but found 229 - filling the rest with NULL
     cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26:4: INSERT failed:     NOT NULL constraint failed: Image.Width_OrigHoechst
     [SQL: 'sqlite3 -nullvalue \'\' -separator , -cmd .import "/Users/shsingh/work/software/cytominer/cytomining/    cytominer-database/.333fc768-fbb4-11e7-9ed2-3c15c2c94e26" "Image" data_d1.sqlite'] (Background on this error at: http://    sqlalche.me/e/4xp6)

**Comment by mcquin** [comment]
We're decided that upstream should be responsible for exporting consistent data.
